package com.learnmesh.enums;

public enum Branch {
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY,
    ELECTRICAL_ENGINEERING,
    ELECTRONICS_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    CHEMICAL_ENGINEERING,
    AERONAUTICAL_ENGINEERING,
    BIOMEDICAL_ENGINEERING
}
